services:
  ollama-amd:
    container_name: ollama-amd
    image: ollama/ollama:rocm
    # pull_policy: always
    healthcheck:
      test: ollama ps || exit 1
      interval: 10s
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - ollama-network
    devices:
      # kfd and dri device access needed for AMDGPU ROCm support to work
      - /dev/kfd
      - /dev/dri
    environment:
      - OLLAMA_HOST=0.0.0.0
      # Keep models loaded in memory for 5 minutes after last use
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_NOHISTORY=1
      # Flash attention (0=disabled, 1=enabled but experimental)
      - OLLAMA_FLASH_ATTENTION=0
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      # 1gb overhead on the GPU
      - OLLAMA_GPU_OVERHEAD=1000000000
    # wierd params from
    # https://github.com/avnigashi/ollama-rocm-docker/blob/main/docker-compose.yml
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "127.0.0.1:11435:8080"
    volumes:
      - ./open-webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama-amd:11434
      - WEBUI_AUTH=False
      - OFFLINE_MODE=true
      - HF_HUB_OFFLINE=1
    depends_on:
      - ollama-amd
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - ollama-network
networks:
  ollama-network:
    driver: "bridge"
